openapi: 3.0.3
info: 
  title:  API de consultório
  description: Irineu, você não sabe e nem eu
  version: 0.0.1
  termsOfService: https://www.google.com
  contact:
    name: Devs Support
    email: fake@devs.com
    url: https://alura.com.br
  license:
    name: GPL license
    url: https://www.gnu.org/licenses/gpl-3.0.html
externalDocs:
  description: documentacao burocrática
  url: https://alura.com.br
servers:
- url: https://google.com
  description: url do servidor a ser requisitado
paths:
  /especialidades: 
    get:
      summary: Recupera todas as especialidades médicas
      responses:
        200:
          description: sucesso 
          content:
            application/json:
              schema:
                 type: array
                 items: 
                   type: object
                 properties: 
                   id:
                     type: integer
                   description:
                     type: string